version: '3'

services:
  lyraimages:
    build:
      context: ./
    container_name: lyraimages
    hostname: raditz
    restart: always
    networks:
      - bridge
    ports:
      - "3202:4000"
    cpuset: "0-5"
    mem_limit: "16g"
    extra_hosts:
      - "localmachine:172.17.0.1"

networks:
  bridge:
    driver: bridge
