version: '3'

services:
  lyratranscript:
    build:
      context: ./
    container_name: lyratranscript
    hostname: nappa
    restart: always
    networks:
      - bridge
    ports:
      - "3201:3000"
    cpuset: "0-5"
    mem_limit: "16g"
    extra_hosts:
      - "localmachine:172.17.0.1"

networks:
  bridge:
    driver: bridge
